import type { PageFonctionnelle } from "./types";

/**
 * Repris de /privacy/ (WordPress, 799 mots) par `npm run migrer:pages`.
 * URL conservée par le plan de migration : ne pas la déplacer.
 */
export const privacy: PageFonctionnelle = {
  slug: "privacy",
  metaTitre: "Privacy Policy – Alps Ski Transfers",
  metaDescription: "",
  h1: "Privacy Policy – Alps Ski Transfers",
  chapo: "Effective Date: 01/03/2025Website: https://alpsskitransfers.com/",
  noindex: true,

  contenu: [
    { type: "paragraphe", texte: "At Alps Ski Transfers, we are committed to protecting your privacy. This Privacy Policy explains how we collect, use, and protect your personal data when you use our website and services. By using https://alpsskitransfers.com/, you agree to the terms outlined in this policy." },
    { type: "titre2", texte: "1. Information We Collect" },
    { type: "paragraphe", texte: "We collect different types of personal information to provide and improve our ski transfer services. This includes:" },
    { type: "titre3", texte: "1.1 Personal Information Provided by You" },
    { type: "liste", items: ["Pick-up and drop-off locations", "Flight details (if applicable)", "Payment information (processed securely through third-party payment gateways)"] },
    { type: "titre3", texte: "1.2 Information Collected Automatically" },
    { type: "paragraphe", texte: "When you visit our website, we may collect the following data automatically:" },
    { type: "liste", items: ["Website usage data (pages visited, time spent, referral sources, etc.)", "Cookies and tracking technologies (see Section 6 for more details)"] },
    { type: "titre2", texte: "2. How We Use Your Information" },
    { type: "paragraphe", texte: "We use your personal data to:✔ Process bookings and payments for your ski resort transfers.✔ Send booking confirmations, service updates, and support messages.✔ Improve our website and services based on user interactions.✔ Ensure customer safety and security during transfers.✔ Comply with legal and regulatory obligations." },
    { type: "paragraphe", texte: "We do not sell, rent, or trade your personal information to third parties." },
    { type: "titre2", texte: "3. Sharing Your Information" },
    { type: "paragraphe", texte: "We only share your data when necessary to provide our transfer services, including:" },
    { type: "titre3", texte: "3.1 Third-Party Service Providers" },
    { type: "liste", items: ["Payment processors (e.g., Stripe, PayPal) for secure transactions.", "Transport providers and drivers to fulfill your booking.", "IT and hosting services for website functionality and security."] },
    { type: "titre3", texte: "3.2 Legal Requirements" },
    { type: "paragraphe", texte: "We may disclose personal data if required by law, court order, or to protect our business, customers, and partners." },
    { type: "titre2", texte: "4. Data Security & Protection" },
    { type: "paragraphe", texte: "We implement strong security measures to protect your data from unauthorized access, alteration, disclosure, or destruction, including:" },
    { type: "liste", items: ["SSL encryption for secure online transactions.", "Restricted access to personal data (only authorized personnel).", "Regular security audits to prevent breaches."] },
    { type: "paragraphe", texte: "While we take all reasonable steps to protect your data, no system is 100% secure, so we encourage users to take precautions when sharing personal information online." },
    { type: "titre2", texte: "5. Data Retention Policy" },
    { type: "paragraphe", texte: "We retain your personal information for as long as necessary to:" },
    { type: "liste", items: ["Fulfill your ski transfer booking.", "Comply with legal obligations (e.g., tax, financial reporting).", "Resolve disputes and customer inquiries."] },
    { type: "paragraphe", texte: "After this period, your data is securely deleted or anonymized." },
    { type: "titre2", texte: "6. Cookies & Tracking Technologies" },
    { type: "titre3", texte: "6.2 How We Use Cookies" },
    { type: "paragraphe", texte: "We use cookies to:✔ Improve website functionality and speed.✔ Analyze site traffic and user behavior.✔ Personalize your experience (e.g., remembering preferences)." },
    { type: "titre3", texte: "6.3 Managing Cookies" },
    { type: "paragraphe", texte: "You can accept, reject, or manage cookies via your browser settings. Disabling cookies may affect website performance." },
    { type: "paragraphe", texte: "For detailed information, refer to our Cookie Policy." },
    { type: "titre2", texte: "7. Your Data Rights" },
    { type: "paragraphe", texte: "✔ Access the personal data we hold about you.✔ Correct or update any inaccurate information.✔ Request deletion of your data (subject to legal requirements).✔ Withdraw consent for marketing communications at any time.✔ Object to data processing under certain conditions." },
    { type: "paragraphe", texte: "To exercise these rights, contact us at [customer support email]." },
    { type: "titre2", texte: "8. Third-Party Links" },
    { type: "paragraphe", texte: "Our website may contain links to external sites (e.g., ski resorts, travel agencies). We are not responsible for the privacy practices of these third parties. We recommend reviewing their privacy policies before sharing personal data." },
    { type: "titre2", texte: "9. Marketing & Communications" },
    { type: "titre3", texte: "9.1 Promotional Emails & Newsletters" },
    { type: "liste", items: ["Special offers on ski transfers.", "Discount codes and promotions.", "Travel updates and useful ski trip tips."] },
    { type: "paragraphe", texte: "You can unsubscribe anytime by clicking the \"Unsubscribe\" link in our emails." },
    { type: "titre3", texte: "9.2 Targeted Advertising" },
    { type: "paragraphe", texte: "We may use cookies and tracking tools to show personalized ads based on your browsing history. You can manage ad preferences through browser settings or ad platforms." },
    { type: "titre2", texte: "10. Children's Privacy" },
    { type: "paragraphe", texte: "Our services are not intended for children under 16 years old. If we discover that a minor has provided personal data, we will delete it immediately. Parents can contact us to request data removal." },
    { type: "titre2", texte: "11. Changes to Our Privacy Policy" },
    { type: "paragraphe", texte: "We may update this Privacy Policy periodically. Any changes will be posted on this page with the updated effective date. We encourage users to review the policy regularly." },
    { type: "paragraphe", texte: "If significant changes are made, we will notify customers via email or website notice." },
    { type: "titre2", texte: "12. Contact Us" },
    { type: "paragraphe", texte: "For questions or concerns about this Privacy Policy, contact us:" },
    { type: "paragraphe", texte: "📧 Email: customerservice@alpsskitransfers.com📞 Phone: +337 69 78 91 89🌍 Website: https://alpsskitransfers.com/" },
    { type: "paragraphe", texte: "By using our services, you agree to the terms outlined in this Privacy Policy." },
  ],

  faq: [
    { question: "6.1 What Are Cookies?", reponse: "Cookies are small text files stored on your device that help us enhance your browsing experience." },
  ],
};
